# Realm Settings Menu Configuration
# All GUI elements can be customized here
# Use standard Minecraft material names for items
# Use color codes (&) or hex colors (#RRGGBB) and gradients ({#RRGGBB>RRGGBB}text{/#})

realm_settings:
  title: "{#6677ee>99ffcc}Realms | Settings: [name]{/#}"
  size: 36
  elements:
    info_item:
      slot: 4
      material: "WRITTEN_BOOK"
      name: "{#6677ee>99ffcc}Settings Info{/#}"
      lore:
        - "{#6677ee>99ffcc}Realm settings for: [name]{/#}"
    
    player_limit:
      slot: 11
      material: "CLOCK"
      name: "{#6677ee>99ffcc}Player Limit{/#}"
      lore:
        - "{#6677ee>99ffcc}Current: [limit] players{/#}"
        - "{#6677ee>99ffcc}Left-click: Increase by 1{/#}"
        - "{#6677ee>99ffcc}Right-click: Decrease by 1{/#}"
        - "{#6677ee>99ffcc}Shift+Click: +/-5{/#}"
    
    set_spawn_point:
      slot: 15
      material: "COMPASS"
      name: "{#6677ee>99ffcc}Set Spawn Point{/#}"
      lore:
        - "{#6677ee>99ffcc}Set the spawn point for this Realm{/#}"
    
    back_button:
      slot: 31
      material: "BARRIER"
      name: "{#ff5555>ff9999}Back{/#}"
      lore:
        - "{#ff5555>ff9999}Return to Realm Management{/#}"
    
    glass_panes:
      material: "BLACK_STAINED_GLASS_PANE"
      name: " "
      fill_remaining: true