# Language Settings
# Available languages: en (English), es (Spanish), id (Indonesian)
language: "en"

# World Settings
max-realms-per-player: 3 # The maximum number of realms a player can own (requires separate permissions for more)
default-world-type: "FLAT" # Default world type on creation: FLAT or NORMAL
default-max-players: 8 # Default maximum number of players allowed in a realm

# Inventory Settings
separate-inventories: true # Enable/disable separate inventories for realms

# Limits
invite-timeout-seconds: 60 # Time in seconds before an invitation expires

# World Border Settings
world-borders: true # Enable/disable world borders globally
default-world-border: true # Default setting for new players (true/false)
default-border-color: "BLUE" # Default border color: BLUE, GREEN, RED