# Realm Settings Menu Configuration
# All GUI elements can be customized here
# Use standard Minecraft material names for items
# Use color codes (&) or hex colors (#RRGGBB) and gradients ({#RRGGBB>RRGGBB}text{/#})

realm_settings:
  title: "<gold>Settings: <white>%realm_name%</white></gold>"
  size: 36
  elements:
    info_item:
      slot: 4
      material: "WRITTEN_BOOK"
      name: "<yellow>Realm Settings</yellow>"
      lore:
        - "<gray>Settings for: <white>%realm_name%</white></gray>"
    
    player_limit:
      slot: 11
      material: "CLOCK"
      name: "<aqua>Player Limit</aqua>"
      lore:
        - "<gray>Current: <white>%limit%</white> players</gray>"
        - "<white>Left-click: <green>Increase by 1</green></white>"
        - "<white>Right-click: <red>Decrease by 1</red></white>"
        - "<white>Shift+Click: <yellow>+/-5</yellow></white>"
    
    set_spawn_point:
      slot: 15
      material: "COMPASS"
      name: "<aqua>Set Spawn Point</aqua>"
      lore:
        - "<gray>Set the spawn point for this Realm</gray>"
    
    back_button:
      slot: 31
      material: "BARRIER"
      name: "<red>Back</red>"
      lore:
        - "<gray>Return to Realm Management</gray>"
    
    glass_panes:
      material: "BLACK_STAINED_GLASS_PANE"
      name: " "
      fill_remaining: true